[Feat] 블록 관련 API 구현
GIGEDI/GIGEDI-BE pull request #33
Opened 2024-11-07 18:02 UTC by cowboysj

## #️⃣ 관련 이슈
- #20 

## 💡 작업내용
- Soft Delete로 구현하였습니다.
1. 블록 생성 API 구현
2. 블록 제목 수정 API 구현
3. 블록 조회 API 구현
4. 블록 삭제 API 구현

## 📸 스크린샷(선택)
|블록 조회 |블록 제목 수정|
|------|---|
|![image](https://github.com/user-attachments/assets/b7bb3612-483e-4d94-a327-dcbe0e440baf)|![image](https://github.com/user-attachments/assets/9244b3b1-4882-416d-9bf4-1b53ab641400)|

블록 생성|블록 삭제|
|---|--|
|![image](https://github.com/user-attachments/assets/80cf9c59-7a9e-4b8f-8cf0-a00694018986)|<img alt="image" src="https://github.com/user-attachments/assets/933494ab-17ff-493a-9175-3734be736fda">|

## 📝 기타
(참고사항, 리뷰어에게 전하고 싶은 말 등을 넣어주세요)

2024-11-08 09:47 UTC, iiqcov requested changes
현재 기능명세서의 사항이 반영 되지 않은 부분이 있는 것 같습니다!
- 아카이브 내 블록 개수 제한 (20개)
- 아카이브 내 동일 제목의 블록 존재 시 제목 뒤에 (n) 추가
- 블록 생성 요청 시 제목이 없을 경우 `New Block`으로 자동 설정

위 부분들에 대해 추가 구현해주세요~

2024-11-08 09:47 UTC, iiqcov commented on src/main/java/gigedi/dev/domain/block/application/BlockService.java
> +        return blocks;
만들어진 `blocks` 객체를 한 번 정의하고 return 하는 것이 아니라 바로 return 할 수 있을 것 같습니다!
``` java
  return blockRepository.findByArchive~
```
이런 방식으로요!

2024-11-08 09:47 UTC, iiqcov commented on src/main/java/gigedi/dev/domain/block/application/BlockService.java
> +    public Archive getArchiveById(Long archiveId) {
해당 메소드에 의해 `ArchiveRepository`를 의존하게 되는데 `ArchiveService`에 따로 메소드를 만들고 거기에서의 서비스를 의존하게 만들어서 특정 도메인의 레포지토리의 의존성을 줄이게 만들면 좋을 것 같아요!

2024-11-08 09:47 UTC, iiqcov commented on src/main/java/gigedi/dev/domain/block/application/BlockService.java
> +    private final FigmaRepository figmaRepository;
`FigmaRepository`를 사용하는 곳이 있을까요? 없다면 삭제해도 좋을 것 같습니다~

2024-11-08 09:47 UTC, iiqcov commented on src/main/java/gigedi/dev/domain/block/domain/Block.java
> +    @Setter
setter 보다는 명시적인 메소드를 설정하여 값을 업데이트 하는 것이 더 좋을 것 같습니다!

2024-11-08 09:47 UTC, iiqcov commented on src/main/java/gigedi/dev/domain/block/application/BlockService.java
> +                block.getWidth());
`CreateBlockResponse`를 만들 때 필요한 객체 정보가 block만 존재하는데, dto의 객체 안에 생성자를 따로 정의하여 `block`만 인자로 받을 수 있도록 만들면 서비스 로직이 더 간단해질 것 같아요!

2024-11-08 09:47 UTC, iiqcov commented on src/main/java/gigedi/dev/domain/block/dto/response/GetBlockResponse.java
> +public class GetBlockResponse {
저희 기능에 블록 클릭 시 해당 위치로 이동되도록 하려면 좌표 및 크기 정보도 넘겨주어야 하지 않을까요?

2024-11-08 17:19 UTC, cowboysj commented on src/main/java/gigedi/dev/domain/block/application/BlockService.java
> +        return blocks;
그렇게 할까 하다가 가독성이 조금 떨어질 것 같아서 변경하였는데 바로 반환하는 방식으로 수정하겠습니다~!

2024-11-08 17:19 UTC, cowboysj commented on src/main/java/gigedi/dev/domain/block/dto/response/GetBlockResponse.java
> +public class GetBlockResponse {
앗 넹 수정했습니다~!

2024-11-08 17:22 UTC, cowboysj commented on src/main/java/gigedi/dev/domain/block/application/BlockService.java
> +    public Archive getArchiveById(Long archiveId) {
넵 수정하였습니다!

2024-11-09 06:34 UTC, iiqcov approved these changes

2024-11-09 06:34 UTC, merged